= Resources to check

List of resources related to distributed systems and more... ;)

== Sessions

=== Spanner

* https://research.google.com/pubs/pub45855.html : Spanner, TrueTime and the CAP Theorem
* https://www.cockroachlabs.com/blog/living-without-atomic-clocks : Living Without Atomic Clocks

=== Raft

* https://raft.github.io/raft.pdf : In Search of an Understandable Consensus Algorithm

=== Transaction isolation (ACID vs. CAP)

* http://www.bailis.org/blog/linearizability-versus-serializability : Linearizability versus Serializability
* http://pmg.csail.mit.edu/papers/adya-phd.pdf : Weak Consistency: A Generalized Theory and Optimistic Implementations for Distributed Transactions (Atul Adya)
* https://arxiv.org/pdf/1302.0309.pdf : highly available transactions: virtues and limitations
* https://www.youtube.com/watch?v=5ZjhNTM8XU8 : "Transactions: myths, surprises and opportunities" (Martin Kleppmann)
* https://hal.inria.fr/file/index/docid/555588/filename/techreport.pdf : A comprehensive study of Convergent and Commutative Replicated Data Types
* http://www.se-radio.net/2016/03/se-radio-episode-252-christopher-meiklejohn-on-crdts : SE-Radio Episode 252: Christopher Meiklejohn on CRDTs
* http://www.cs.princeton.edu/~wlloyd/papers/challenges-hotos15.pdf : Challenges to Adopting Stronger Consistency at Scale

=== Blockchain

* https://bitcoin.org/bitcoin.pdf : Bitcoin: A Peer-to-Peer Electronic Cash System
* https://www.stellar.org/papers/stellar-consensus-protocol.pdf : The Stellar Consensus Protocol: A Federated Model for Internet-level Consensus
* http://www.se-radio.net/2017/07/se-radio-episode-297-kieren-james-lubin-on-blockchain/ : SE-Radio Episode 297: Kieren James-Lubin on Blockchain
* https://eng.paxos.com/why-arent-distributed-systems-engineers-working-on-blockchain-technology : Why aren’t distributed systems engineers working on blockchain technology?

=== Paxos

* https://github.com/dgryski/awesome-consensus : nice summary of paxos articles
* http://research.microsoft.com/en-us/um/people/lamport/pubs/paxos-simple.pdf : Paxos made simple, Lamport
* https://www.youtube.com/watch?v=JEpsBg0AO6o : nice youtube video of showing how paxos works
* https://arxiv.org/abs/1802.07000 : CASPaxos, Ritsov

== Disttributed system resources

https://www.youtube.com/watch?v=D5iCl12MuRw::
  Martin Kleppmann presentation of difference Sequential Consistency versus Linearizability. +
  The talk is summary of research paper "Sequential consistency versus linearizability" by H. Attiya and J.L. Welch +
https://github.com/rystsov/perseus::
  by Denis Rystsov, set of scripts to investigate a distributed database's responsiveness
  when one of its three nodes is isolated from the peers
http://blog.christianposta.com/microservices/the-hardest-part-about-microservices-data::
  blog post about microservice architecture, event sourcing [#kafka, #debezium, #cqrs, #msa]
https://kafemlejnek.tv/dil-6-nastupujici-architektury-web-aplikaci, https://kafemlejnek.tv/dil-7-kafka-samza-druid-io::
  kafemlejnek.tv interview about cqrs, kafka, samza, druid.io [#msa] (CZ)
http://www.javamagazine.mozaicreader.com/JanFeb2018/Twitter/69/0/3922765#&pageSet=69&page=0&contentItem=3922765::
  Java Magazine Jan/Feb 2018, CQRS with Java EE [#javaee, #cqrs, #msa] (note about Kafka version 0.11 and transactional producers,
  see https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging,
  https://cwiki.apache.org/confluence/display/KAFKA/KIP-129%3A+Streams+Exactly-Once+Semantics)
https://youtu.be/yC6b0709HCw::
  What we talk about when we talk about Distributed Systems, presentation by Alvaro Videla (RabbitMQ),
  talk on basic terms and how they bind together
https://disco.ethz.ch/courses/podc_allstars::
  Principles of Distributed Computing (lecture collection) from ETH Zurich
https://github.com/dist-research/articles::
  Cohesive list of articles and papers on distributed systems (Paxos, Raft...)

